//! The generated C companion to the shim, `pycc_ext_exports.inc`.
//!
//! Extracted from `src/ext_build.rs` by #1455 under `AGENTS.md`'s
//! decomposability rule, unchanged except for the copy-kind table it now
//! appends.

use super::*;

/// Renders the generated C companion to [`SHIM_C`]: the module name macros,
/// the user-exception-class table ([`exception_classes_c`]), one
/// `METH_FASTCALL` wrapper per export, the module-level `PyMethodDef`
/// table, one type object per published class (`method_types_c`), and the
/// MRO table that answers `isinstance` for a carrier of any class in
/// `carriers` (#1435, `carrier_class_isinstance_c`), and the per-class
/// table the shared `__copy__` consults (#1455, `carrier_class_copy_kinds_c`).
///
/// `module_name` is already known to be a valid ASCII Python identifier
/// (`ext_output::resolve` rejects everything else before this runs). An
/// export name is **no longer** a Python identifier by construction: a
/// method's compiled name is `pycc_hir::class`'s dotted mangling, so every
/// C identifier built from it goes through `pycc_codegen::mangle_ext_name`
/// first. What survives of the old invariant is what it was for -- the
/// pieces pasted into C source are a module name, a class name, a method
/// name and a mangled derivation of the three, and none can carry a
/// character that would escape it.
///
/// The export list is **partitioned** on [`ExtExport::class`]. A
/// module-level function keeps its `pycc_ext_methods[]` row unchanged --
/// a table the shim's `pycc_ext_publish` binds one row at a time, as each
/// definition executes, rather than `PyModuleDef.m_methods` (#1199); a
/// method goes into its own class's table instead, because a row in
/// `pycc_ext_methods[]` would publish exactly the flat `mod."Class.method"`
/// attribute the type object exists to avoid. A PEP 562 module hook
/// (#1467) goes into `pycc_ext_module_hooks[]` rather than
/// `pycc_ext_methods[]`, because the shim may add it only after the module
/// body has run.
///
/// This form installs no comparison or hash slot (#1427) and no attribute
/// descriptor (#1442, #1448): it is [`generate_exports_inc_with_slots`] with
/// neither, kept for the generated-text tests that predate #1427. Both
/// builds call that variant: the `--ext` build with its descriptors and
/// slots, and since #1470 the embedded build with its slots only.
#[cfg(test)]
pub(crate) fn generate_exports_inc(
    module_name: &str,
    exports: &[ExtExport],
    classes: &[UserExceptionClass],
    publications: &[ExtPublishedClass],
    ctors: &[ExtCtor],
    carriers: &[ExtCarrierClass],
) -> String {
    generate_exports_inc_with_slots(
        module_name,
        exports,
        classes,
        publications,
        ctors,
        carriers,
        &[],
        &[],
    )
}

/// The generated companion for a program whose carrier classes resolve
/// comparison or hash dunders (#1427) or carry attribute descriptors
/// (#1448), as the test-only `generate_exports_inc` is for one with
/// neither: `getsets` is [`super::collect_carrier_getsets`]' output and
/// `slots` is [`super::collect_slot_dunders`]', both of which
/// `method_types_c` installs.
/// The `--ext` build driver and (#1470, with no descriptors) the embedded
/// build call this form; the generated-text tests that predate #1427 call
/// the slot-free one.
#[allow(clippy::too_many_arguments)]
pub(crate) fn generate_exports_inc_with_slots(
    module_name: &str,
    exports: &[ExtExport],
    classes: &[UserExceptionClass],
    publications: &[ExtPublishedClass],
    ctors: &[ExtCtor],
    carriers: &[ExtCarrierClass],
    getsets: &[ExtClassGetsets],
    slots: &[ExtSlotDunders],
) -> String {
    let mut out = String::new();
    out.push_str("/* Generated by pycc --ext. Do not edit: see src/ext_build.rs. */\n");
    out.push_str(&format!("#define PYCC_EXT_MODULE_NAME {module_name}\n"));
    out.push_str(&format!(
        "#define PYCC_EXT_MODULE_NAME_STR \"{module_name}\"\n\n"
    ));
    out.push_str(&exception_classes_c(classes));
    for export in exports {
        out.push_str(&wrapper_for(export));
    }
    let module_level = || exports.iter().filter(|export| export.class.is_none());
    out.push_str(&module_method_table(
        "pycc_ext_methods",
        module_level().filter(|export| !is_module_hook(&export.name)),
    ));
    // #1467: a PEP 562 hook is added by `pycc_ext_exec_module` only once
    // the module body has run (see `module_hooks`). Always emitted, as the
    // bare sentinel when the module defines no hook, so the shim can name
    // the table unconditionally.
    out.push_str(&module_method_table(
        "pycc_ext_module_hooks",
        module_level().filter(|export| is_module_hook(&export.name)),
    ));
    out.push_str(&method_types_c(publications, ctors, getsets, slots));
    out.push_str(&carrier_class_isinstance_c(carriers));
    out.push_str(&carrier_class_copy_kinds_c(carriers));
    out
}

/// One module-level `PyMethodDef` table named `table`, sentinel included.
fn module_method_table<'a>(table: &str, exports: impl Iterator<Item = &'a ExtExport>) -> String {
    let mut out = format!("static PyMethodDef {table}[] = {{\n");
    for export in exports {
        // A module-level function's bare name, its mangled name and its
        // wrapper suffix are all the same string -- the mangling is the
        // identity for a dot-free name -- so this row keeps its single-`name`
        // format. The divergence between `ml_name` and the wrapper symbol
        // belongs to the per-class tables.
        out.push_str(&format!(
            "    {{\"{name}\", (PyCFunction)(void (*)(void))pycc_ext_wrap_{name}, \
             {flags}, NULL}},\n",
            name = export.name,
            flags = super::keywords::method_flags("METH_FASTCALL", export),
        ));
    }
    out.push_str("    {NULL, NULL, 0, NULL},\n};\n\n");
    out
}
