//! Part 2 of #566 (D-243): the production capture and verification test behind
//! the Architecture evidence hero.
//!
//! The hero on `site/architecture/index.html` claims that one production
//! fixture, `tests/fixtures/quick_start.py`, crosses every implemented compiler
//! stage and produces a native executable whose stdout is a known 26 bytes.
//! This test is the thing that makes the claim checkable: it re-derives every
//! checked-in stage artifact under `tests/fixtures/architecture-trace/` through
//! the crates' *public* APIs, compares the re-derivation byte for byte with the
//! checked-in bytes, and then runs the real `pycc` binary end to end.
//!
//! Division of labour (no duplicated checks):
//!
//! * this file owns **re-derivation** — that the checked-in artifacts are what
//!   today's compiler actually produces, that the type-checked HIR really is
//!   byte-identical to the finalized HIR, and that the native build and its
//!   stdout are what the hero says;
//! * `scripts/site_pipeline_evidence.py` owns the **record** — the SHA-256
//!   identities in `trace.json`, the hero record's shape, and the visible page
//!   projection;
//! * `tests/site_evidence.rs` owns the **per-hero manifest facts** and never
//!   re-runs the pipeline.
//!
//! Regenerating the artifacts after a deliberate compiler change is one step:
//!
//! ```text
//! PYCC_ARCHITECTURE_TRACE_OUT=tests/fixtures/architecture-trace \
//!     cargo test --test architecture_trace regeneration
//! ```
//!
//! With the variable unset the same test writes into a scratch directory and
//! compares, so the regeneration path is the verified path. Regenerated bytes
//! still have to be re-pinned by hand in `trace.json` and on the page: that
//! re-pinning is the review step, and the SHA-256 identities are checked by
//! `scripts/site_pipeline_evidence.py`.

use pycc_scratch::ScratchDir;
use std::path::{Path, PathBuf};
use std::process::Command;

const FIXTURE: &str = "tests/fixtures/quick_start.py";
const TRACE_DIR: &str = "tests/fixtures/architecture-trace";
const EXPECTED_STDOUT: &str = "0\n1\n1\n2\n3\n5\n8\n13\n21\n34\n55\n";
/// How many leading lines of each artifact the page is allowed to excerpt.
/// The page's excerpt is checked against these same bytes by
/// `scripts/site_pipeline_evidence.py`; the constant lives here too so a
/// change to it cannot silently desynchronize the two checkers.
const EXCERPT_LINES: usize = 18;

fn repo_root() -> &'static Path {
    Path::new(env!("CARGO_MANIFEST_DIR"))
}

fn artifact_path(name: &str) -> PathBuf {
    repo_root().join(TRACE_DIR).join(name)
}

/// D-082: remove CR only immediately before LF, so a checked-out artifact
/// compares equal under Git's `autocrlf` without touching any other byte.
fn canonical_lf(bytes: &[u8]) -> Vec<u8> {
    bytes
        .iter()
        .enumerate()
        .filter_map(|(i, &byte)| {
            (byte != b'\r' || bytes.get(i + 1) != Some(&b'\n')).then_some(byte)
        })
        .collect()
}

/// The reviewed comparison: a stage artifact is accepted only when the bytes
/// the compiler produces right now equal the checked-in bytes exactly.
/// Returned as a `Result` rather than asserted so the negative cases below can
/// prove the rejection actually happens.
fn compare_stage(stage: &str, derived: &str, checked_in: &[u8]) -> Result<(), String> {
    let checked_in = canonical_lf(checked_in);
    if derived.as_bytes() == checked_in.as_slice() {
        return Ok(());
    }
    Err(format!(
        "{stage} artifact drifted: re-derivation is {} bytes, checked-in is {} bytes",
        derived.len(),
        checked_in.len()
    ))
}

/// A stage may be presented as implemented only when it actually carries
/// evidence. The LLVM IR stage has none today (`--emit` does not exist), which
/// is why the hero is `partial` and not `all-Tier-1`.
fn present_as_implemented(stage: &str, evidence: Option<usize>) -> Result<usize, String> {
    match evidence {
        Some(bytes) => Ok(bytes),
        None => Err(format!(
            "{stage} has no artifact and must be presented as unavailable, not implemented"
        )),
    }
}

fn read_artifact(name: &str) -> Vec<u8> {
    std::fs::read(artifact_path(name))
        .unwrap_or_else(|e| panic!("missing stage artifact {name}: {e}"))
}

/// The one place the pipeline is driven, so the page, `trace.json` and this
/// test cannot disagree about which public API produced which stage.
struct Derived {
    parser: String,
    hir: String,
    typed: String,
    mir: String,
}

fn derive() -> Derived {
    let source = std::fs::read_to_string(repo_root().join(FIXTURE)).expect("fixture is readable");
    let source = String::from_utf8(canonical_lf(source.as_bytes())).expect("fixture is UTF-8");
    let parsed = pycc_parser::parse_all(&source).expect("the fixture parses");
    let resolved = pycc_hir::ResolvedImports::default();
    let lowered = pycc_hir::lower_module(&parsed, &resolved).expect("the fixture lowers");
    let linked = pycc_hir::link(vec![pycc_hir::LinkInput {
        display_path: FIXTURE.to_string(),
        module: lowered,
    }])
    .expect("a single-module program links");
    let finalized = pycc_hir::finalize(linked).expect("the linked program finalizes");
    let typed = pycc_types::check_and_resolve_all_keyed(&finalized).expect("the fixture type-checks");
    let mir = pycc_mir::build(&typed);
    let mut mir_text = String::new();
    for item in &mir.items {
        mir_text.push_str(&format!("{item:#?}\n"));
    }
    Derived {
        parser: format!("{parsed:#?}\n"),
        hir: format!("{finalized:#?}\n"),
        typed: format!("{typed:#?}\n"),
        mir: mir_text,
    }
}

/// The three artifacts this trace checks in, paired with the field of
/// [`Derived`] that produces each one.
fn stage_files(derived: &Derived) -> [(&'static str, &String); 3] {
    [
        ("parser-ast.txt", &derived.parser),
        ("hir-module.txt", &derived.hir),
        ("mir-items.txt", &derived.mir),
    ]
}

/// Raw environment read, kept branch-free so the regeneration override and the
/// scratch-directory default are decided by [`out_dir`] alone.
fn configured_out_dir() -> Option<std::ffi::OsString> {
    std::env::var_os("PYCC_ARCHITECTURE_TRACE_OUT")
}

fn out_dir(configured: Option<std::ffi::OsString>, fallback: &Path) -> PathBuf {
    match configured {
        Some(value) => repo_root().join(value),
        None => fallback.to_path_buf(),
    }
}

/// The single writer of the checked-in stage artifacts. Verification runs it
/// into a scratch directory; regeneration runs the same function into the
/// fixture directory.
fn write_stage_artifacts(dir: &Path, derived: &Derived) {
    for (name, text) in stage_files(derived) {
        std::fs::write(dir.join(name), text).expect("stage artifact is writable");
    }
}

/// The byte counts pinned in `trace.json`, which the page also publishes.
fn pinned_bytes() -> serde_json::Value {
    let raw = std::fs::read(repo_root().join(TRACE_DIR).join("trace.json")).expect("trace.json");
    serde_json::from_slice(&raw).expect("trace.json is JSON")
}

#[test]
fn checked_in_stage_artifacts_are_what_the_compiler_produces_today() {
    let derived = derive();
    compare_stage("parser", &derived.parser, &read_artifact("parser-ast.txt")).unwrap();
    compare_stage("hir", &derived.hir, &read_artifact("hir-module.txt")).unwrap();
    compare_stage("mir", &derived.mir, &read_artifact("mir-items.txt")).unwrap();
}

#[test]
fn regeneration_writes_exactly_the_checked_in_stage_artifacts() {
    let scratch = ScratchDir::new("architecture_trace_out").expect("scratch directory");
    let dir = out_dir(configured_out_dir(), &scratch);
    let derived = derive();
    write_stage_artifacts(&dir, &derived);
    for (name, _) in stage_files(&derived) {
        let written = canonical_lf(&std::fs::read(dir.join(name)).expect("written artifact"));
        assert_eq!(
            written,
            canonical_lf(&read_artifact(name)),
            "regenerating {name} would change the checked-in bytes"
        );
    }
}

#[test]
fn the_pinned_byte_counts_in_trace_json_describe_the_checked_in_artifacts() {
    let pinned = pinned_bytes();
    for (identity, name) in [
        ("source", "../quick_start.py"),
        ("parser", "parser-ast.txt"),
        ("hir", "hir-module.txt"),
        ("type-check", "hir-module.txt"),
        ("mir", "mir-items.txt"),
    ] {
        let actual = canonical_lf(&read_artifact(name)).len();
        assert_eq!(
            pinned["artifacts"][identity]["bytes"].as_u64(),
            Some(actual as u64),
            "trace.json pins the wrong byte count for {identity}"
        );
    }
    assert_eq!(pinned["stdout"]["bytes"].as_u64(), Some(26));
    assert_eq!(pinned["stdout"]["text"].as_str(), Some(EXPECTED_STDOUT));
    assert_eq!(pinned["native"]["exit_status"].as_u64(), Some(0));
    assert_eq!(pinned["excerpt_lines"].as_u64(), Some(EXCERPT_LINES as u64));
}

#[test]
fn type_checking_returns_hir_byte_identical_to_the_finalized_hir() {
    // The hero presents type checking as an *identity* claim rather than as a
    // fourth artifact: `check_and_resolve_all_keyed` accepts this fixture
    // without rewriting any node, so the two stages share one SHA-256. If that
    // ever stops being true the page's claim is wrong and this fails first.
    let derived = derive();
    assert_eq!(
        derived.typed, derived.hir,
        "type-checked HIR is no longer byte-identical to the finalized HIR; \
         the architecture hero's identity claim must be replaced by its own artifact"
    );
}

#[test]
fn the_page_excerpts_are_exact_prefixes_of_the_artifacts() {
    for name in ["parser-ast.txt", "hir-module.txt", "mir-items.txt"] {
        let bytes = canonical_lf(&read_artifact(name));
        let text = String::from_utf8(bytes).expect("stage artifacts are UTF-8");
        let excerpt: Vec<&str> = text.lines().take(EXCERPT_LINES).collect();
        assert_eq!(excerpt.len(), EXCERPT_LINES, "{name} is shorter than its excerpt");
        let prefix = format!("{}\n", excerpt.join("\n"));
        assert!(text.starts_with(&prefix), "{name} excerpt is not a prefix");
    }
}

#[test]
fn the_fixture_builds_a_native_executable_whose_stdout_is_the_published_transcript() {
    let scratch = ScratchDir::new("architecture_trace").expect("scratch directory");
    let binary = scratch.join("quick_start");
    let build = Command::new(env!("CARGO_BIN_EXE_pycc"))
        .args(["build", FIXTURE, "-o", binary.to_str().unwrap()])
        .current_dir(repo_root())
        .output()
        .expect("could not execute the production pycc binary");
    assert_eq!(build.status.code(), Some(0), "{build:?}");
    let run = Command::new(&binary).output().expect("native executable runs");
    assert_eq!(run.status.code(), Some(0), "{run:?}");
    assert!(run.stderr.is_empty(), "unexpected stderr: {run:?}");
    assert_eq!(run.stdout, EXPECTED_STDOUT.as_bytes(), "stdout transcript drift");
    assert_eq!(run.stdout.len(), 26, "published stdout byte count drift");
}

#[test]
fn a_mutated_artifact_a_foreign_artifact_and_an_unevidenced_stage_are_all_rejected() {
    let derived = derive();
    // 1. One mutated byte in an otherwise correct artifact.
    let mut mutated = canonical_lf(&read_artifact("hir-module.txt"));
    mutated[0] = b'X';
    assert!(
        compare_stage("hir", &derived.hir, &mutated)
            .unwrap_err()
            .contains("hir artifact drifted")
    );
    // 2. A different fixture's artifact presented as this stage's: the MIR of
    //    the same program is not its HIR, and byte length alone does not save it.
    assert!(
        compare_stage("hir", &derived.hir, &read_artifact("mir-items.txt"))
            .unwrap_err()
            .contains("hir artifact drifted")
    );
    // 3. An omitted stage presented as implemented.
    assert_eq!(present_as_implemented("mir", Some(derived.mir.len())), Ok(derived.mir.len()));
    assert!(
        present_as_implemented("llvm-ir", None)
            .unwrap_err()
            .contains("must be presented as unavailable")
    );
    // 4. The positive control: the shipped artifacts still compare equal.
    assert_eq!(
        compare_stage("parser", &derived.parser, &read_artifact("parser-ast.txt")),
        Ok(())
    );
    // 5. The regeneration override resolves to the fixture directory when the
    //    environment names one, and to the caller's scratch directory otherwise.
    let fallback = repo_root().join("target");
    assert_eq!(out_dir(None, &fallback), fallback);
    assert_eq!(
        out_dir(Some(std::ffi::OsString::from(TRACE_DIR)), &fallback),
        repo_root().join(TRACE_DIR)
    );
    assert!(configured_out_dir().is_none() || configured_out_dir().is_some());
    assert_eq!(canonical_lf(b"a\r\nb\r"), b"a\nb\r");
}
