#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Builds an index table from each entry's own frontmatter.

Generated rather than maintained because a hand-kept index drifts from the files
it indexes, and a drifted index is worse than none: it is read as authoritative.
`--check` makes staleness a gate failure instead of something noticed months
later.

Only the table is generated, between the markers below. Everything else in the
README is prose owned by whoever wrote it — a generator that rewrites the whole
file makes explaining the format impossible.

Usage:
  uv run scripts/generate-index.py docs/decisions docs/decisions/README.md
  uv run scripts/generate-index.py docs/todo docs/todo/README.md --prefix T- --label Todo
  uv run scripts/generate-index.py docs/decisions docs/decisions/README.md --check
"""
import argparse
import re
import sys
from pathlib import Path

START = "<!-- index:start -->"
END = "<!-- index:end -->"

FRONTMATTER = re.compile(r"\A---\n(.*?)\n---", re.DOTALL)


def field(block: str, name: str) -> str | None:
    m = re.search(rf"^{name}:\s*(.+?)\s*$", block, re.MULTILINE)
    if not m:
        return None
    v = m.group(1)
    if len(v) >= 2 and v[0] == v[-1] == '"':  # noqa: PLR2004 — a quoted YAML scalar
        v = v[1:-1].replace('\\"', '"').replace("\\\\", "\\")
    return v


def entries(dir_: Path, prefix: str = "D-") -> tuple[list[tuple[str, str, str, str]], list[str]]:
    rows, errors = [], []
    for f in sorted(dir_.glob(f"{prefix}*.md")):
        text = f.read_text(encoding="utf-8")
        m = FRONTMATTER.match(text)
        if not m:
            errors.append(f"{f.name}: no frontmatter block")
            continue
        block = m.group(1)
        missing = [k for k in ("id", "title", "status") if field(block, k) is None]
        if missing:
            errors.append(f"{f.name}: frontmatter missing {', '.join(missing)}")
            continue
        ident, title, status = (field(block, k) or "" for k in ("id", "title", "status"))
        if not f.name.startswith(f"{ident}-"):
            errors.append(f"{f.name}: filename does not start with its id {ident!r}")
            continue
        rows.append((ident, title, status, f.name))
    return rows, errors


def render(rows: list[tuple[str, str, str, str]], label: str = "Decision") -> str:
    """The table, and only the table — the prose around it belongs to its author."""
    head = f"| ID | {label} | Status |\n| --- | --- | --- |\n"
    body = "".join(
        f"| [{ident}](./{name}) | {title} | {status} |\n" for ident, title, status, name in rows
    )
    return head + body


NEW_FILE_HEADER = (
    "<!-- Generated by scripts/generate-index.py. Do not edit by hand. -->\n"
    "<!-- The prose that explains this directory lives in README.md. -->\n\n"
)


def splice(readme: str, table: str) -> str:
    """Replace what is between the markers, appending them if absent."""
    if not readme.strip():
        return f"{NEW_FILE_HEADER}{START}\n{table}{END}\n"
    if START in readme and END in readme:
        head, rest = readme.split(START, 1)
        _, tail = rest.split(END, 1)
        return f"{head}{START}\n{table}{END}{tail}"
    sep = "" if readme.endswith("\n\n") else ("\n" if readme.endswith("\n") else "\n\n")
    return f"{readme}{sep}{START}\n{table}{END}\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("entries_dir", type=Path)
    ap.add_argument("readme_path", type=Path)
    ap.add_argument("--prefix", default="D-")
    ap.add_argument("--label", default="Decision")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()

    if not a.entries_dir.is_dir():
        print(f"no such directory: {a.entries_dir}")
        return 0

    rows, errors = entries(a.entries_dir, a.prefix)
    if errors:
        for e in errors:
            print(f"  {e}")
        return 1

    have = a.readme_path.read_text(encoding="utf-8") if a.readme_path.is_file() else ""
    want = splice(have, render(rows, a.label))

    if a.check:
        if want != have:
            print(f"{a.readme_path} is stale — regenerate it "
                  f"(uv run scripts/generate-index.py {a.entries_dir} {a.readme_path}"
                  f"{'' if a.prefix == 'D-' else f' --prefix {a.prefix}'})")
            return 1
        print(f"{a.readme_path} is up to date ({len(rows)} entries).")
        return 0

    a.readme_path.write_text(want, encoding="utf-8")
    print(f"{len(rows)} entries -> {a.readme_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
