use super::fixture::{AARCH64, BASE, ElfSpec, X86_64, elf_bytes};
use super::*;

#[test]
fn a_library_reads_every_tag_in_order() {
    let spec = ElfSpec::library("libnat.so.1", &["libdep.so.2", "libc.so.6"])
        .rpath("/opt/r")
        .runpath("$ORIGIN/../lib");
    let image = parse_elf(&elf_bytes(&spec))
        .expect("parses")
        .expect("an image");
    assert_eq!(image.machine, X86_64);
    assert!(!image.program);
    assert_eq!(image.soname.as_deref(), Some("libnat.so.1"));
    assert_eq!(image.needed, ["libdep.so.2", "libc.so.6"]);
    assert_eq!(image.rpath.as_deref(), Some("/opt/r"));
    assert_eq!(image.runpath.as_deref(), Some("$ORIGIN/../lib"));
}

#[test]
fn a_program_is_marked_and_a_module_has_no_soname() {
    let mut spec = ElfSpec::module(&["libnat.so.1"]);
    spec.program = true;
    spec.machine = AARCH64;
    let image = parse_elf(&elf_bytes(&spec))
        .expect("parses")
        .expect("an image");
    assert!(image.program);
    assert_eq!(image.machine, AARCH64);
    assert_eq!(image.soname, None);
    assert_eq!(image.runpath, None);
}

#[test]
fn other_files_are_not_images() {
    assert_eq!(parse_elf(b"").expect("ok"), None);
    assert_eq!(parse_elf(b"not an elf file").expect("ok"), None);
    let mut elf32 = elf_bytes(&ElfSpec::module(&[]));
    elf32[4] = 1;
    assert_eq!(parse_elf(&elf32).expect("ok"), None);
    let mut big = elf_bytes(&ElfSpec::module(&[]));
    big[5] = 2;
    assert_eq!(parse_elf(&big).expect("ok"), None);
    assert!(is_elf_magic(&elf32));
    assert!(!is_elf_magic(b"\xcf\xfa\xed\xfe"));
}

#[test]
fn every_truncation_is_an_error() {
    let bytes = elf_bytes(&ElfSpec::library("libx.so", &["liby.so"]));
    // Header, program header table, dynamic section, and the strings.
    for cut in [
        10,
        40,
        58,
        64 + 20,
        64 + 56 + 30,
        bytes.len() - 20,
        bytes.len() - 1,
    ] {
        let error = parse_elf(&bytes[..cut]).expect_err(&format!("cut at {cut}"));
        assert!(
            error.contains("runs past the end") || error.contains("outside"),
            "{cut}: {error}"
        );
    }
}

#[test]
fn offsets_that_overflow_are_errors() {
    let mut bytes = elf_bytes(&ElfSpec::module(&["liby.so"]));
    bytes[32..40].copy_from_slice(&u64::MAX.to_le_bytes());
    let error = parse_elf(&bytes).expect_err("phoff overflows");
    assert!(error.contains("program header table"), "{error}");
}

#[test]
fn a_string_table_outside_every_load_segment_is_an_error() {
    let mut bytes = elf_bytes(&ElfSpec::module(&["liby.so"]));
    // The PT_LOAD's vaddr moves away from where DT_STRTAB points.
    let vaddr = 64 + 16;
    bytes[vaddr..vaddr + 8].copy_from_slice(&(BASE * 4).to_le_bytes());
    let error = parse_elf(&bytes).expect_err("strtab unmapped");
    assert!(error.contains("string table"), "{error}");
}

#[test]
fn a_string_index_outside_the_file_is_an_error() {
    let spec = ElfSpec::module(&["liby.so"]);
    let mut bytes = elf_bytes(&spec);
    // The first dynamic entry is DT_NEEDED; point its value far away.
    let dyn_off = bytes.len() - 16 * 3;
    bytes[dyn_off + 8..dyn_off + 16].copy_from_slice(&(1u64 << 40).to_le_bytes());
    let error = parse_elf(&bytes).expect_err("string outside");
    assert!(error.contains("outside the file"), "{error}");
    bytes[dyn_off + 8..dyn_off + 16].copy_from_slice(&u64::MAX.to_le_bytes());
    assert!(parse_elf(&bytes).is_err());
}

#[test]
fn no_dynamic_segment_or_no_string_table_means_no_dependencies() {
    let mut bytes = elf_bytes(&ElfSpec::module(&["liby.so"]));
    // Second program header is PT_DYNAMIC; retype it to PT_NOTE.
    bytes[64 + 56..64 + 60].copy_from_slice(&4u32.to_le_bytes());
    let image = parse_elf(&bytes).expect("parses").expect("an image");
    assert!(image.needed.is_empty());
    let mut bytes = elf_bytes(&ElfSpec::module(&["liby.so"]));
    // The DT_STRTAB entry (second to last) becomes an unknown tag.
    let at = bytes.len() - 32;
    bytes[at..at + 8].copy_from_slice(&0x7000_0000u64.to_le_bytes());
    let image = parse_elf(&bytes).expect("parses").expect("an image");
    assert!(image.needed.is_empty());
}

#[test]
fn ldconfig_output_maps_names_to_paths_in_cache_order() {
    let stdout = "1234 libs found in cache `/etc/ld.so.cache'\n\
        \tlibssl.so.3 (libc6,x86-64) => /lib/x86_64-linux-gnu/libssl.so.3\n\
        \tlibssl.so.3 (libc6) => /lib/i386-linux-gnu/libssl.so.3\n\
        \tlibz.so.1 (libc6,AArch64, OS ABI: Linux 3.7.0) => /lib/aarch64-linux-gnu/libz.so.1\n\
        \tlibbare.so => /opt/bare/libbare.so\n\
        \t (libc6) => /nowhere\n\
        \tlibempty.so (libc6) => \n\
        Cache generated by: ldconfig (GNU libc) stable release version 2.39\n";
    let map = parse_ldconfig(stdout);
    assert_eq!(
        map["libssl.so.3"],
        [
            PathBuf::from("/lib/x86_64-linux-gnu/libssl.so.3"),
            PathBuf::from("/lib/i386-linux-gnu/libssl.so.3")
        ]
    );
    assert_eq!(
        map["libz.so.1"],
        [PathBuf::from("/lib/aarch64-linux-gnu/libz.so.1")]
    );
    assert_eq!(map["libbare.so"], [PathBuf::from("/opt/bare/libbare.so")]);
    assert_eq!(map.len(), 3);
}

#[test]
fn search_dirs_expand_origin_and_drop_unmodelled_entries() {
    let dirs = search_dirs(
        "$ORIGIN/../lib::${ORIGIN}:/opt/abs:$LIB/x:/p/$PLATFORM",
        Path::new("/site/pkg"),
    );
    assert_eq!(
        dirs,
        [
            (PathBuf::from("/site/pkg/../lib"), true),
            (PathBuf::from("/site/pkg"), true),
            (PathBuf::from("/opt/abs"), false),
        ]
    );
}
