//! The `pycc.lock` file: its schema, its canonical rendering and its
//! parser (the pycc.lock decision entry, rule 5). The file is generated,
//! byte-stable across hosts (sorted, `/` separators, `\n` line ends, no
//! absolute path or timestamp) and refused on any unknown field.

use serde::Deserialize;
use std::path::Path;

/// The lock file's name.
pub(crate) const LOCK_FILE_NAME: &str = "pycc.lock";

/// The only schema version this pycc reads and writes.
pub(crate) const LOCK_VERSION: i64 = 1;

/// A whole lock file.
#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct Lock {
    pub(crate) version: i64,
    #[serde(default)]
    pub(crate) target: Vec<LockTarget>,
}

/// One (entry, triple) section.
#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
#[serde(deny_unknown_fields, rename_all = "kebab-case")]
pub(crate) struct LockTarget {
    pub(crate) entry: String,
    pub(crate) triple: String,
    pub(crate) python: String,
    pub(crate) cache_tag: String,
    pub(crate) platform: String,
    /// The sha256 of the interpreter's shared libpython, or of its `LIBPL`
    /// static archive when it is configured without one (#1272).
    pub(crate) libpython_sha256: String,
    /// The program's required direct roots (rule 2).
    pub(crate) roots: Vec<String>,
    /// The program's optional direct roots (#1290): roots imported only
    /// inside the body of a `try` whose handler catches `ImportError`, and
    /// not required elsewhere. An optional root no installed distribution
    /// owns is recorded here with no package. Rendered only when non-empty,
    /// so a lock with no optional root is byte-identical to one written
    /// before the field existed; an older pycc refuses the field as
    /// unknown.
    #[serde(default)]
    pub(crate) optional_roots: Vec<String>,
    #[serde(default)]
    pub(crate) package: Vec<LockedPackage>,
    #[serde(default)]
    pub(crate) native: Vec<LockedNative>,
}

/// One locked distribution.
#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
#[serde(deny_unknown_fields, rename_all = "kebab-case")]
pub(crate) struct LockedPackage {
    pub(crate) name: String,
    pub(crate) version: String,
    pub(crate) site: String,
    pub(crate) files: u64,
    pub(crate) tree_sha256: String,
    pub(crate) requires: Vec<String>,
}

/// One native library a closure image needs outside the interpreter and
/// the system directories (the pycc.lock decision entry, rule 8; #1243).
#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
#[serde(deny_unknown_fields, rename_all = "kebab-case")]
pub(crate) struct LockedNative {
    pub(crate) name: String,
    pub(crate) sha256: String,
    pub(crate) required_by: Vec<String>,
}

/// A TOML basic string.
fn quote(text: &str) -> String {
    let mut out = String::with_capacity(text.len() + 2);
    out.push('"');
    for ch in text.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            ch if ch < ' ' || ch == '\u{7f}' => out.push_str(&format!("\\u{:04X}", ch as u32)),
            ch => out.push(ch),
        }
    }
    out.push('"');
    out
}

fn quote_list(items: &[String]) -> String {
    let mut sorted = items.to_vec();
    sorted.sort();
    let quoted: Vec<String> = sorted.iter().map(|item| quote(item)).collect();
    format!("[{}]", quoted.join(", "))
}

/// Renders `lock` canonically: sections by (entry, triple), packages and
/// natives by name, lists sorted.
pub(crate) fn render(lock: &Lock) -> String {
    let mut out = format!(
        "# Generated by `pycc lock`. Do not edit.\nversion = {}\n",
        lock.version
    );
    let mut targets: Vec<&LockTarget> = lock.target.iter().collect();
    targets.sort_by(|a, b| (&a.entry, &a.triple).cmp(&(&b.entry, &b.triple)));
    for target in targets {
        out.push_str("\n[[target]]\n");
        for (key, value) in [
            ("entry", &target.entry),
            ("triple", &target.triple),
            ("python", &target.python),
            ("cache-tag", &target.cache_tag),
            ("platform", &target.platform),
            ("libpython-sha256", &target.libpython_sha256),
        ] {
            out.push_str(&format!("{key} = {}\n", quote(value)));
        }
        out.push_str(&format!("roots = {}\n", quote_list(&target.roots)));
        if !target.optional_roots.is_empty() {
            out.push_str(&format!(
                "optional-roots = {}\n",
                quote_list(&target.optional_roots)
            ));
        }
        let mut packages: Vec<&LockedPackage> = target.package.iter().collect();
        packages.sort_by(|a, b| a.name.cmp(&b.name));
        for package in packages {
            out.push_str(&format!(
                "\n[[target.package]]\nname = {}\nversion = {}\nsite = {}\nfiles = {}\n\
                 tree-sha256 = {}\nrequires = {}\n",
                quote(&package.name),
                quote(&package.version),
                quote(&package.site),
                package.files,
                quote(&package.tree_sha256),
                quote_list(&package.requires)
            ));
        }
        let mut natives: Vec<&LockedNative> = target.native.iter().collect();
        natives.sort_by(|a, b| a.name.cmp(&b.name));
        for native in natives {
            out.push_str(&format!(
                "\n[[target.native]]\nname = {}\nsha256 = {}\nrequired-by = {}\n",
                quote(&native.name),
                quote(&native.sha256),
                quote_list(&native.required_by)
            ));
        }
    }
    out
}

/// Parses a lock file's text, refusing another schema version, an unknown
/// field, an `entry` with an empty, `.` or `..` component (so an absolute one
/// too), a duplicate (entry, triple) section, a non-Tier-1 triple or
/// an unknown `site`.
pub(crate) fn parse(text: &str) -> Result<Lock, String> {
    let invalid =
        |e: &dyn std::fmt::Display| format!("{LOCK_FILE_NAME} is not a valid lock file: {e}");
    let value: toml::Value = toml::from_str(text).map_err(|e| invalid(&e))?;
    match value.get("version").and_then(toml::Value::as_integer) {
        Some(LOCK_VERSION) => {}
        Some(other) => {
            return Err(format!(
                "{LOCK_FILE_NAME} has schema version {other}; this pycc reads version \
                 {LOCK_VERSION} -- regenerate it with this pycc's `pycc lock`"
            ));
        }
        None => return Err(invalid(&"it has no integer `version`")),
    }
    let lock: Lock = value.try_into().map_err(|e| invalid(&e))?;
    let mut seen = std::collections::BTreeSet::new();
    for target in &lock.target {
        if target
            .entry
            .split('/')
            .any(|part| matches!(part, "" | "." | ".."))
        {
            return Err(invalid(&format!(
                "entry `{}` has an empty, `.` or `..` component; it must be a canonical relative path below the lock's directory",
                target.entry
            )));
        }
        if !crate::TIER1_TARGETS.contains(&target.triple.as_str()) {
            return Err(invalid(&format!(
                "`{}` is not a Tier-1 target triple",
                target.triple
            )));
        }
        if !seen.insert((&target.entry, &target.triple)) {
            return Err(invalid(&format!(
                "two sections for entry `{}` on `{}`",
                target.entry, target.triple
            )));
        }
        if let Some(package) = target
            .package
            .iter()
            .find(|package| !matches!(package.site.as_str(), "purelib" | "platlib"))
        {
            return Err(invalid(&format!(
                "package `{}` has site `{}`, not `purelib` or `platlib`",
                package.name, package.site
            )));
        }
    }
    Ok(lock)
}

/// Inserts, replaces or (given `None`) removes the (entry, triple) section.
pub(crate) fn replace_target(
    mut lock: Lock,
    entry: &str,
    triple: &str,
    derived: Option<LockTarget>,
) -> Lock {
    lock.target
        .retain(|target| !(target.entry == entry && target.triple == triple));
    lock.target.extend(derived);
    lock
}

/// Drops every section whose entry no longer names a file under `lock_dir`.
pub(crate) fn prune(mut lock: Lock, lock_dir: &Path) -> Lock {
    lock.target
        .retain(|target| lock_dir.join(&target.entry).is_file());
    lock
}

/// The host's Tier-1 triple from `std::env::consts`-style `arch` and `os`.
pub(crate) fn host_triple(arch: &str, os: &str) -> Result<String, String> {
    let vendor_os = match os {
        "macos" => "apple-darwin",
        "linux" => "unknown-linux-gnu",
        "windows" => "pc-windows-msvc",
        other => other,
    };
    let triple = format!("{arch}-{vendor_os}");
    if crate::TIER1_TARGETS.contains(&triple.as_str()) {
        Ok(triple)
    } else {
        Err(format!(
            "`pycc lock` runs on a Tier-1 host; this host is `{arch}` `{os}`, which is not one \
             (see `pycc version --verbose`)"
        ))
    }
}

#[cfg(test)]
#[path = "schema_tests.rs"]
mod tests;
