use super::*;

fn target(entry: &str, triple: &str) -> LockTarget {
    LockTarget {
        entry: entry.into(),
        triple: triple.into(),
        python: "3.14.7".into(),
        cache_tag: "cpython-314".into(),
        platform: "macosx-11.0-arm64".into(),
        libpython_sha256: "ab".repeat(32),
        roots: vec!["zeta".into(), "alpha".into()],
        package: vec![
            LockedPackage {
                name: "zeta".into(),
                version: "2".into(),
                site: "platlib".into(),
                files: 3,
                tree_sha256: "cd".repeat(32),
                requires: vec!["b".into(), "a".into()],
            },
            LockedPackage {
                name: "alpha".into(),
                version: "1.0".into(),
                site: "purelib".into(),
                files: 1,
                tree_sha256: "ef".repeat(32),
                requires: vec![],
            },
        ],
        native: vec![],
    }
}

fn lock(targets: Vec<LockTarget>) -> Lock {
    Lock {
        version: LOCK_VERSION,
        target: targets,
    }
}

#[test]
fn render_is_canonical_and_round_trips() {
    let one = lock(vec![
        target("z/main.py", "aarch64-apple-darwin"),
        target("a.py", "x86_64-unknown-linux-gnu"),
        target("a.py", "aarch64-apple-darwin"),
    ]);
    let mut reversed = one.clone();
    reversed.target.reverse();
    let text = render(&one);
    assert_eq!(text, render(&reversed));
    assert!(text.starts_with("# Generated by `pycc lock`. Do not edit.\nversion = 1\n\n[[target]]\nentry = \"a.py\"\ntriple = \"aarch64-apple-darwin\"\n"));
    assert!(
        text.contains("roots = [\"alpha\", \"zeta\"]\n\n[[target.package]]\nname = \"alpha\"\n")
    );
    assert!(text.contains("requires = [\"a\", \"b\"]\n"));
    assert!(!text.contains('\r'));
    let parsed = parse(&text).unwrap();
    assert_eq!(render(&parsed), text);
    assert_eq!(parsed.target.len(), 3);
}

#[test]
fn natives_render_and_parse() {
    let mut with_native = target("a.py", "aarch64-apple-darwin");
    with_native.native = vec![
        LockedNative {
            name: "libz.dylib".into(),
            sha256: "00".repeat(32),
            required_by: vec!["zeta".into()],
        },
        LockedNative {
            name: "liba.dylib".into(),
            sha256: "11".repeat(32),
            required_by: vec![],
        },
    ];
    let text = render(&lock(vec![with_native]));
    assert!(text.contains("[[target.native]]\nname = \"liba.dylib\"\nsha256 = "));
    assert!(text.contains("required-by = [\"zeta\"]\n"));
    assert_eq!(render(&parse(&text).unwrap()), text);
}

#[test]
fn strings_are_escaped_as_toml_basic_strings() {
    assert_eq!(
        quote("a\"b\\c\nd\te\rf\u{1}g\u{7f}é"),
        "\"a\\\"b\\\\c\\nd\\te\\rf\\u0001g\\u007Fé\""
    );
    let text = render(&lock(vec![target(
        "dir \"q\"/ü\\x.py",
        "aarch64-apple-darwin",
    )]));
    assert_eq!(parse(&text).unwrap().target[0].entry, "dir \"q\"/ü\\x.py");
}

#[test]
fn bad_lock_files_are_refused() {
    let valid = render(&lock(vec![target("a.py", "aarch64-apple-darwin")]));
    let err = parse(&valid.replace("version = 1", "version = 2")).unwrap_err();
    assert!(err.contains("schema version 2"), "{err}");
    assert!(
        parse("version = \"1\"\n")
            .unwrap_err()
            .contains("no integer `version`")
    );
    assert!(
        parse("not toml ===")
            .unwrap_err()
            .contains("pycc.lock is not a valid lock file")
    );
    let err = parse(&valid.replace("python = ", "surprise = 1\npython = ")).unwrap_err();
    assert!(err.contains("surprise"), "{err}");
    let err =
        parse(&valid.replace("aarch64-apple-darwin", "riscv64-unknown-linux-gnu")).unwrap_err();
    assert!(err.contains("not a Tier-1 target triple"), "{err}");
    let err = parse(&valid.replace("\"purelib\"", "\"elsewhere\"")).unwrap_err();
    assert!(err.contains("site `elsewhere`"), "{err}");
    let doubled = render(&lock(vec![
        target("a.py", "aarch64-apple-darwin"),
        target("a.py", "aarch64-apple-darwin"),
    ]));
    assert!(
        parse(&doubled)
            .unwrap_err()
            .contains("two sections for entry `a.py`")
    );
    // An empty lock (no sections) is valid.
    assert!(parse("version = 1\n").unwrap().target.is_empty());
}

#[test]
fn replace_target_keeps_others_replaces_and_removes() {
    let base = lock(vec![
        target("a.py", "aarch64-apple-darwin"),
        target("a.py", "x86_64-unknown-linux-gnu"),
        target("b.py", "aarch64-apple-darwin"),
    ]);
    let mut changed = target("a.py", "aarch64-apple-darwin");
    changed.python = "3.14.8".into();
    let replaced = replace_target(base.clone(), "a.py", "aarch64-apple-darwin", Some(changed));
    assert_eq!(replaced.target.len(), 3);
    assert_eq!(
        replaced
            .target
            .iter()
            .filter(|t| t.python == "3.14.8")
            .count(),
        1
    );
    let removed = replace_target(base.clone(), "a.py", "aarch64-apple-darwin", None);
    assert_eq!(removed.target.len(), 2);
    assert!(
        removed
            .target
            .iter()
            .all(|t| !(t.entry == "a.py" && t.triple == "aarch64-apple-darwin"))
    );
    let inserted = replace_target(
        base,
        "c.py",
        "aarch64-apple-darwin",
        Some(target("c.py", "aarch64-apple-darwin")),
    );
    assert_eq!(inserted.target.len(), 4);
}

#[test]
fn prune_drops_sections_whose_entry_is_gone() {
    let dir = pycc_scratch::ScratchDir::new("lock_schema_prune").unwrap();
    std::fs::create_dir(dir.join("app")).unwrap();
    std::fs::write(dir.join("app/main.py"), "").unwrap();
    std::fs::create_dir(dir.join("gone.py")).unwrap();
    let pruned = prune(
        lock(vec![
            target("app/main.py", "aarch64-apple-darwin"),
            target("deleted.py", "aarch64-apple-darwin"),
            target("gone.py", "aarch64-apple-darwin"),
        ]),
        &dir,
    );
    let entries: Vec<_> = pruned.target.iter().map(|t| t.entry.as_str()).collect();
    assert_eq!(entries, ["app/main.py"]);
}

#[test]
fn host_triples_map_to_tier_one() {
    assert_eq!(
        host_triple("aarch64", "macos").unwrap(),
        "aarch64-apple-darwin"
    );
    assert_eq!(
        host_triple("x86_64", "linux").unwrap(),
        "x86_64-unknown-linux-gnu"
    );
    assert_eq!(
        host_triple("x86_64", "windows").unwrap(),
        "x86_64-pc-windows-msvc"
    );
    let err = host_triple("riscv64", "linux").unwrap_err();
    assert!(err.contains("not one") && err.contains("riscv64"), "{err}");
    assert!(host_triple("x86_64", "freebsd").is_err());
}
