#!/usr/bin/env python3
"""Generate docs/decisions/README.md's index table from every decision
file's own frontmatter. The index is a build artifact -- never hand-edit
it; run this script after adding or changing a decision file, and its
--check mode verifies the committed file is current.
"""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path

FRONTMATTER_RE = re.compile(
    r'\A---\nid: (D-\d+)\ntitle: "((?:[^"\\]|\\.)*)"\nstatus: (\S+)\n---\n'
)

PREAMBLE = """# pycc Design Decisions (ADR log)

Format: one file per irreversible-ish call, under this directory. Statuses:
`proposed` -> `accepted` -> (`superseded by D-xxx`). Changing an accepted
decision requires a new entry, not an edit -- see `TEMPLATE.md`.

This table is generated by `scripts/generate_decisions_index.py` from every
`D-*.md` file's own frontmatter. Never hand-edit it -- run the generator
after adding or changing a decision file; `--check` verifies it is
current."""


def unescape_yaml(value):
    return value.replace('\\"', '"').replace("\\\\", "\\")


def read_frontmatter(path):
    text = path.read_text(encoding="utf-8")
    m = FRONTMATTER_RE.match(text)
    if not m:
        raise ValueError(f"{path}: missing or malformed frontmatter")
    id_, title_escaped, status = m.groups()
    return id_, unescape_yaml(title_escaped), status


def check_unique_ids(entries):
    """Fail closed on a duplicate D-NNN id across distinct decision files.

    Two files each claiming the same numeric prefix (e.g. two files whose
    frontmatter both say ``id: D-201``) makes every cross-reference to that
    number ambiguous. Regenerating the index from such a tree must not
    silently produce a README with two rows for the same id -- it must
    raise instead, so both the plain-generate and ``--check`` paths fail
    closed on the same defect class as
    https://github.com/rotnov/pycc/issues/803.
    """
    seen: dict[str, str] = {}
    for id_, _title, _status, filename in entries:
        if id_ in seen:
            raise ValueError(
                f"duplicate decision id {id_}: claimed by both "
                f"{seen[id_]} and {filename}"
            )
        seen[id_] = filename


def check_filename_matches_id(entries):
    """Fail closed when a filename's own D-NNN prefix disagrees with its
    frontmatter id.

    ``check_unique_ids`` only dedups on the frontmatter id, so a file named
    ``D-201-second.md`` whose frontmatter claims ``id: D-999`` would pass
    that check while still recreating the ambiguous-numbering defect class
    from https://github.com/rotnov/pycc/issues/803: the README links D-999
    at a path a reader would expect to hold D-201, and a future file
    legitimately named D-201-... collides with a path that already exists.
    """
    for id_, _title, _status, filename in entries:
        if not filename.startswith(f"{id_}-") and filename != f"{id_}.md":
            raise ValueError(
                f"{filename}: filename prefix does not match its "
                f"frontmatter id {id_}"
            )


def generate_index(decisions_dir):
    entries = []
    for path in sorted(decisions_dir.glob("D-*.md")):
        id_, title, status = read_frontmatter(path)
        entries.append((id_, title, status, path.name))
    entries.sort(key=lambda e: int(e[0].split("-")[1]))
    check_unique_ids(entries)
    check_filename_matches_id(entries)

    lines = [PREAMBLE, "", "| ID | Decision | Status |", "|---|---|---|"]
    for id_, title, status, filename in entries:
        lines.append(f"| [{id_}](./{filename}) | {title} | {status} |")
    return "\n".join(lines) + "\n"


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("decisions_dir", type=Path)
    parser.add_argument("readme_path", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    try:
        generated = generate_index(args.decisions_dir)
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 1

    if args.check:
        current = (
            args.readme_path.read_text(encoding="utf-8")
            if args.readme_path.exists()
            else ""
        )
        if generated != current:
            diff = "".join(
                difflib.unified_diff(
                    current.splitlines(keepends=True),
                    generated.splitlines(keepends=True),
                    fromfile=str(args.readme_path),
                    tofile="generated",
                )
            )
            print(
                f"{args.readme_path} is out of date with its source files:\n{diff}",
                file=sys.stderr,
            )
            return 1
        print(f"{args.readme_path} is up to date.")
        return 0

    args.readme_path.write_text(generated, encoding="utf-8")
    print(f"wrote {args.readme_path} ({generated.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
