[package]
name = "pycc_types"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
pycc_hir = { path = "../pycc_hir" }
pycc_diag = { path = "../pycc_diag" }
pycc_std = { path = "../pycc_std" }

[dev-dependencies]
pycc_mir = { path = "../pycc_mir" }
pycc_parser = { path = "../pycc_parser" }
