pub use ruff_python_ast::{
    Arguments, CmpOp, ConversionFlag, ElifElseClause, Expr, ExprBinOp, ExprBooleanLiteral,
    ExprCall, ExprCompare, ExprContext, ExprFString, ExprName, ExprNumberLiteral,
    ExprStringLiteral, ExprUnaryOp, Identifier, InterpolatedElement, InterpolatedStringElement,
    InterpolatedStringLiteralElement, ModModule, Number, Operator, Parameters, Stmt, StmtAssign,
    StmtExpr, StmtFor, StmtFunctionDef, StmtIf, StmtReturn, StmtWhile, UnaryOp,
};
pub use ruff_text_size::{Ranged, TextRange};

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn re_exports_are_the_same_type_as_upstream() {
        fn assert_same_type<T>(_: T) {}
        let m = ModModule {
            node_index: Default::default(),
            range: Default::default(),
            body: Default::default(),
        };
        assert_same_type::<ruff_python_ast::ModModule>(m);
    }

    #[test]
    fn re_exported_grammar_types_resolve_and_have_the_expected_shape() {
        // Every assertion below extracts a value via a re-exported type's
        // `.as_xxx()` accessor (generated by ruff's own `is_macro::Is`
        // derive) plus `.unwrap()`, not a hand-rolled `let PATTERN = ...
        // else { panic!(...) }` -- per TESTING.md's own documented
        // coverage guidance, `.unwrap()`'s panic branch lives in
        // libcore/libstd, outside this crate's instrumented regions, so it
        // never reads as an uncovered region the way a hand-written
        // panic arm would (confirmed: an earlier draft using `let-else`
        // panics left 11 regions uncovered, one per never-taken panic arm).
        // The point of this test is still to fail to *compile* if a
        // re-export is missing or misnamed.
        let module = parse_test_source("x = 1\ny = x + 2\n");
        let first = module.body[0].as_assign_stmt().unwrap();
        assert_eq!(first.targets.len(), 1);
        let second = module.body[1].as_assign_stmt().unwrap();
        let bin_op = second.value.as_bin_op_expr().unwrap();
        assert_eq!(bin_op.op, Operator::Add);

        let module =
            parse_test_source("if y == 3:\n    pass\nelif True:\n    pass\nelse:\n    pass\n");
        let if_stmt = module.body[0].as_if_stmt().unwrap();
        let compare = if_stmt.test.as_compare_expr().unwrap();
        assert_eq!(compare.ops[0], CmpOp::Eq);
        assert_eq!(if_stmt.elif_else_clauses.len(), 2);
        assert!(if_stmt.elif_else_clauses[0].test.is_some());
        assert!(if_stmt.elif_else_clauses[1].test.is_none());
        let elif_test = if_stmt.elif_else_clauses[0].test.as_ref().unwrap();
        let elif_bool = elif_test.as_boolean_literal_expr().unwrap();
        assert!(elif_bool.value);

        let module = parse_test_source("while y < 10:\n    pass\n");
        assert!(module.body[0].as_while_stmt().is_some());

        let module = parse_test_source("for i in range(3):\n    pass\n");
        let for_stmt = module.body[0].as_for_stmt().unwrap();
        assert!(!for_stmt.is_async);
        let target = for_stmt.target.as_name_expr().unwrap();
        assert_eq!(target.ctx, ExprContext::Store);

        let module = parse_test_source("z = -y\n");
        let assign = module.body[0].as_assign_stmt().unwrap();
        let unary = assign.value.as_unary_op_expr().unwrap();
        assert_eq!(unary.op, UnaryOp::USub);

        let module = parse_test_source("s = \"hi\"\n");
        let assign = module.body[0].as_assign_stmt().unwrap();
        let string_lit = assign.value.as_string_literal_expr().unwrap();
        assert_eq!(string_lit.value.to_str(), "hi");

        let module = parse_test_source("f = f\"{y}\"\n");
        let assign = module.body[0].as_assign_stmt().unwrap();
        let fstring = assign.value.as_f_string_expr().unwrap();
        let elements: Vec<_> = fstring.value.elements().collect();
        assert_eq!(elements.len(), 1);
        assert!(elements[0].as_interpolation().is_some());

        assert_eq!(Number::Float(1.5), Number::Float(1.5));
    }

    fn parse_test_source(source: &str) -> ModModule {
        ruff_python_parser::parse_module(source)
            .unwrap()
            .into_syntax()
    }
}
